### ISSUE TITLE
Output is HTML Escaped

### ISSUE THREAD

**Issue by Arcitec** [ddormer/markdown-to-bbcode#1]
Thanks for creating one of the best Markdown to BBCode converters.

Unfortunately, https://ddormer.github.io/markdown-to-bbcode-site/ is kinda useless right now, because the BBCode is rendered with escaped HTML entities by the commonmark library, and then put in an "as-is" textedit field by you.

Try writing this in the markdown box: `"Hello World"`

The result is: `&quot;Hello World&quot;` which is illegal BBCode.

I had to go into the browser console to fix the output, by running this:

```
var doc = new DOMParser().parseFromString(document.getElementById("bbcode").textContent, "text/html"); document.getElementById("bbcode").textContent = doc.documentElement.textContent;
```

Perhaps commonmark has some better fix for this, such as "generate without escaping content"? I have no idea. But I still appreciate your project and am using it with the console fix/hack above. :)

**Comment by Arcitec** [comment]
Oh, another issue with the output is that paragraphs are separated by three newlines.

Input:

```
Paragraph one.

Paragraph two.

Paragraph three.
```

Output:

```
Paragraph one.


Paragraph two.


Paragraph three.
```

Edit: A very hacky "fix" (not a true fix) for that is this regex method:

```
var doc = new DOMParser().parseFromString(document.getElementById("bbcode").textContent, "text/html"); document.getElementById("bbcode").textContent = doc.documentElement.textContent.replace(/\n\n\n/g, "\n\n");
```

**Comment by Arcitec** [comment]
Another issue is that lists are incorrectly formatted.

Input:

```
## Frequently Asked Questions:

- Q: Question one.
- A: Answer one.

- Q: Question two.
- A: Answer two.
```

Output:

```
[b][size=6]Frequently Asked Questions:[/size][/b]
[list]
[*]
Q: Question one.

[*]
A: Answer one.

[*]
Q: Question two.

[*]
A: Answer two.

[/list]
```

Expected output (best):

```
[b][size=6]Frequently Asked Questions:[/size][/b]

[list]
[*]Q: Question one.
[*]A: Answer one.
[/list]

[list]
[*]Q: Question two.
[*]A: Answer two.
[/list]
```

Expected output (acceptable but not as good):

```
[b][size=6]Frequently Asked Questions:[/size][/b]

[list]
[*]Q: Question one.
[*]A: Answer one.

[*]Q: Question two.
[*]A: Answer two.
[/list]
```

I don't say this to criticize. Just to let you know about these formatting issues. Your converter is probably the best one out there anyway, since everything else I found created completely unusable output. :)

**Comment by ddormer** [comment]
Hi Bananaman, thanks for your feedback and the project compliments! (even though this project was a hacked up side-project for a separate side-project **;)**)

I agree that all of the things you mentioned should be fixed; I'm unfortunately quite busy at the moment and can't immediately improve the project. I may be able to squeeze in some bug fixes in the next month, but I will happily review PRs in the meantime.
