### ISSUE TITLE
How to render special characters?

### ISSUE THREAD

**Issue by harrystuart** [ddormer/markdown-to-bbcode#4]
Hey mate, thanks for sharing this. Just a quick one, I am finding that the following markdown:

```md
* **Historical Lien:** Partial discharge of mortgage. Mortgagee: Galloway & Co. ({{41}}).
```

renders to:

```md
[list]
[*][b]Historical Lien:[/b] Partial discharge of mortgage. Mortgagee: Galloway &amp; Co. ({{41}}).
[/list]
```

I'd like to retain the `&` character. This occurs with other special characters such as `"`. Any thoughts? Thank you

**Comment by ddormer** [comment]
Hi, you're welcome! All text is html-escaped by default, to disable escaping you can instantiate the `BBCodeRenderer` with an options object like this:
`var writer = new markdown_to_bbcode.BBCodeRenderer({esc: (text) => text});`

**Comment by harrystuart** [comment]
Brilliant, thanks.
